### ISSUE TITLE
Unable to install certificate

### ISSUE THREAD

**Issue by jareware** [dlapiduz/letsencrypt-s3front#12]
Initially, I was getting this error during cert installation to CloudFront:

```
An unexpected error occurred:
ClientError: An error occurred (InvalidViewerCertificate) when calling the UpdateDistribution operation: Your IAMCertificateId does not match the given Certificate field.
```

I thought this might be due to there already existing a certificate for the distribution, so I removed that.

But now I'm getting:

```
An unexpected error occurred:
ClientError: An error occurred (InvalidViewerCertificate) when calling the UpdateDistribution operation: Cannot specify IAMCertificateId and a CertificateSource not equal to "iam".
```

Ideas?

**Comment by jareware** [comment]
The certs themselves are fine, as I'm able to just grab them after the failure and successfully upload them with `$ aws iam upload-server-certificate` from the shell.

**Comment by jareware** [comment]
I also tried patching https://github.com/dlapiduz/letsencrypt-s3front/blob/master/letsencrypt_s3front/installer.py#L69 to also set:

    cf_cfg['DistributionConfig']['ViewerCertificate']['CertificateSource'] = 'iam'

but no cigar.

**Comment by jareware** [comment]
From the logs, this is what we GET for the distribution config:

```xml
    <ViewerCertificate>
        <CertificateSource>cloudfront</CertificateSource>
        <MinimumProtocolVersion>SSLv3</MinimumProtocolVersion>
        <CloudFrontDefaultCertificate>true</CloudFrontDefaultCertificate>
    </ViewerCertificate>
```

And this is what we POST back:

```xml
    <ViewerCertificate>
        <MinimumProtocolVersion>SSLv3</MinimumProtocolVersion>
        <IAMCertificateId>REDACTED</IAMCertificateId>
        <CertificateSource>iam</CertificateSource>
    </ViewerCertificate>
```

The value for `<IAMCertificateId>` is definitely the same as in the response to uploading the cert (from the `<ServerCertificateId>` field). So from the error "Your IAMCertificateId does not match the given Certificate field", I really have no idea what "Certificate field" refers to; even http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/PutConfig.html only lists the `<ViewerCertificate>` stuff above.

Any pointers appreciated.

**Comment by dillona** [comment]
I am experiencing this as well

**Comment by dillona** [comment]
I was able to use the web console to set the certificate and everything worked

**Comment by dillona** [comment]
cf_cfg['DistributionConfig']['ViewerCertificate']['Certificate'] = cert_id
        cf_cfg['DistributionConfig']['ViewerCertificate']['CertificateSource'] = 'iam'
        cf_cfg['DistributionConfig']['ViewerCertificate']['SSLSupportMethod'] = 'sni-only'
        cf_cfg['DistributionConfig']['ViewerCertificate']['MinimumProtocolVersion'] = 'TLSv1'

**Comment by jareware** [comment]
Well done! Looking forward to this landing in a release. :)

**Comment by ryansb** [comment]
That should be fixed (partially) with [this commit](https://github.com/dlapiduz/letsencrypt-s3front/commit/984243db7cebd5c9c8da5956e65ea178b08f1bc4) but I'm not sure if it's in a release.

**Comment by ryansb** [comment]
Also, @dillona, the line `cf_cfg['DistributionConfig']['ViewerCertificate']['SSLSupportMethod'] = 'sni-only'` should be configurable since some CF distributions may be paying for the dedicated IP to support non-SNI clients.

**Comment by dillona** [comment]
@ryansb In my PR #13 I only set sni-only as a default if nothing else is already set.
So if you are already paying for the dedicated IPs, nothing will be changed

**Comment by ryansb** [comment]
@dillona Oh, that does handle it. Thanks for pointing that out.

**Comment by dlapiduz** [comment]
That PR was merged so you should be all good to go now. Thanks everyone!
