### ISSUE TITLE
Documentation Help

### ISSUE THREAD

**Issue by grappler** [dlapiduz/letsencrypt-s3front#14]
This seems to be a good solution for automating the updating of SSL certificate.

I am unclear on a few things.

On what computer do I need to install the scripts? Would it be the S3 bucket? I SSH into the bucket and run them?

This command would be run also in the S3 bucket?
```
AWS_ACCESS_KEY_ID="your_key" \
AWS_SECRET_ACCESS_KEY="your_secret" \
letsencrypt --agree-tos -a letsencrypt-s3front:auth \
--letsencrypt-s3front:auth-s3-bucket the_bucket \
[ --letsencrypt-s3front:auth-s3-region your-bucket-region-name ] (default is us-east-1) \
-i letsencrypt-s3front:installer \
--letsencrypt-s3front:installer-cf-distribution-id your_cf_distribution_id \
-d the_domain
```

...and these are the variables that I need to change?
- `your_key`
- `your_secret`
- `the_bucket`
- `your-bucket-region-name`
- `your_cf_distribution_id`
- `the_domain`

My setup is for a images CDN which uses S3 bucket and CloudFront.

**Comment by paulwakeford** [comment]
I am not the author but can help.

> On what computer do I need to install the scripts?

On any that has access to the AWS API endpoints - a local workstation, an EC2 instance, etc.

> and these are the variables that I need to change?

Yes.

I'm hoping this can all be rolled into a single Lambda function so it can be scheduled.

Paul

**Comment by grappler** [comment]
@paulwakeford Thank you explaining it. I tried https://vittegleo.com/blog/letsencrypt-lambda-function/ but was unable to upload the zip file.
