### ISSUE TITLE
acme>=0.1.2 dependency?

### ISSUE THREAD

**Issue by randomphrase** [dlapiduz/letsencrypt-s3front#15]
Hi, trying to install using pip I get an error due to an unsatisfied dependency on acme>=0.1.2:

    alastair@vm-debian ~ » pip install --user letsencrypt-s3front
    Downloading/unpacking letsencrypt-s3front
      Downloading letsencrypt-s3front-0.1.2.tar.gz
      Running setup.py (path:/tmp/pip-build-T2gXST/letsencrypt-s3front/setup.py) egg_info for package letsencrypt-s3front
        
        warning: no files found matching '*' under directory 'docs'
        warning: no files found matching '*' under directory 'letsencrypt_cloudfront/tests/testdata'
    Downloading/unpacking acme>=0.1.2 (from letsencrypt-s3front)
      Could not find a version that satisfies the requirement acme>=0.1.2 (from letsencrypt-s3front) (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151107, 0.0.0.dev20151108, 0.0.0.dev20151114, 0.0.0.dev20151123, 0.0.0.dev20151201, 0.1.0, 0.1.1, 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151107, 0.0.0.dev20151108, 0.0.0.dev20151114, 0.0.0.dev20151123, 0.0.0.dev20151201, 0.1.0, 0.1.1)
    Cleaning up...
    No distributions matching the version for acme>=0.1.2 (from letsencrypt-s3front)
    Storing debug log for failure in /home/alastair/.pip/pip.log

[From what I can tell](https://pypi.python.org/pypi/acme), 0.1.1 is the most recent version of acme, but I could be missing something obvious...

On a related note, is it valid to use the `--user` option as I have done here?

**Comment by lucastan** [comment]
im getting the same issue

**Comment by dlapiduz** [comment]
Sorry about this issue, when I upgraded the plugin I didn't realize the version was tied to the upstream client.

Can you try now with version 0.1.3 of the plugin?

**Comment by randomphrase** [comment]
Seems to work, thanks.
