### ISSUE TITLE
Automating with a Lambda function

### ISSUE THREAD

**Issue by dan-v** [dlapiduz/letsencrypt-s3front#18]
This is an awesome plugin! Thanks for creating this. I put together a quick [how-to](https://vittegleo.com/blog/letsencrypt-lambda-function/) on turning the letsencrypt CLI with this plugin into an AWS Lambda function that can be setup to run on a regular schedule. This gives you a nice automated, server free, hands off process for using this plugin. I figured I'd at least share it here, for anyone interested. As this isn't really an issue, feel free to close.

**Comment by dlapiduz** [comment]
Thanks for the comment, I am looking into moving this into a native function rather than having to spin up an EC2 instance. It shouldn't be that hard...
