### ISSUE TITLE
Renewing every 90 days?

### ISSUE THREAD

**Issue by nowned** [dlapiduz/letsencrypt-s3front#2]
@spittal and I are looking to use this but have you thought of a good way to handle the fact these need to renew every 90 days?

Can this tool be setup on a Cron to automatically connect to the server and re-do the cert, and re-attach it to the Cloudfront install?

Thanks!

**Comment by dlapiduz** [comment]
@nowned I am pretty sure you can, you only need to make sure that you have a secure environment where to run this without exposing your aws credentials and the LE key. The script itself should work fine...
