### ISSUE TITLE
"required or optional" prompt when trying to auto renew

### ISSUE THREAD

**Issue by bradt** [dlapiduz/letsencrypt-s3front#21]
I'm trying to automate the cert renewal and installation with the following command:

```
AWS_ACCESS_KEY_ID="XXXXXXXXXXXXXXXXX" \
AWS_SECRET_ACCESS_KEY="XXXXXXXXXXXXXXXXXXXXXX" \
letsencrypt --agree-tos -a letsencrypt-s3front:auth \
--letsencrypt-s3front:auth-s3-bucket assets.bradt.ca \
-i letsencrypt-s3front:installer \
--letsencrypt-s3front:installer-cf-distribution-id XXXXXXXXXX \
-d assets.bradt.ca --renew-by-default --text
```

Unfortunately I'm still getting the following prompt:

```
Please choose whether HTTPS access is required or optional.
-------------------------------------------------------------------------------
1: Easy - Allow both HTTP and HTTPS access to these sites
2: Secure - Make all requests redirect to secure HTTPS access
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
```

Any ideas how to get rid of it? Is there a CLI switch that I could set?

**Comment by ChrisRut** [comment]
Yes, try: `--no-redirect`

**Comment by Rjs37** [comment]
or --redirect if you want the alternative

**Comment by ChrisRut** [comment]
@Rjs37 , 
Actually, I don't think it matters in the context of this module, because AFAICT this module does not affect the redirect settings of CloudFront, `ViewerProtocolPolicy` is not being set on the update_distribution call: https://github.com/dlapiduz/letsencrypt-s3front/blob/master/letsencrypt_s3front/installer.py#L85-L87

**Comment by Rjs37** [comment]
Fair enough @ChrisRut, in that case pick whichever :D. Though it could be good practice to use your preferred option anyway, in-case the flag is taken into account at a later date.

**Comment by bradt** [comment]
Awesome, `--no-redirect` worked, thanks!
