### ISSUE TITLE
domain.org and www.domain.org signing?

### ISSUE THREAD

**Issue by visibilityspots** [dlapiduz/letsencrypt-s3front#24]
Hi,

I have a blog running on s3 setted up like http://docs.aws.amazon.com/gettingstarted/latest/swh/website-hosting-intro.html

So I have a https://domain.org which is working fine with a letsencrypt cert through your script.

But when surfing through https://www.domain.org it's failing cause the server's certificate doesn't match the url.

I tried adding an additional domain with the -d parameter pointing to www.domain.org but then the script is failing.

```
2016-02-22 03:22:43,064:ERROR:acme.challenges:Unable to reach http://www.domain.org/.well-known/acme-challenge/TvngOJZhOaadrudpmHVXhtl3BXXX: hostname 'www.domain.org' doesn't match 'domain.org'
2016-02-22 03:22:43,064:ERROR:letsencrypt_s3front.authenticator:Self-verify of challenge failed, authorization abandoned!
```

Any idea how I could use the script to get them both signed?

Thanks in advance

**Comment by devjack** [comment]
You need to use -d multiple times.  For example I have the following script setup for my provisioning:

`export LE_DOMAINS=mydomain.com,www.mydomain.com`  (usually in env vars for CI)
```
letsencrypt --agree-tos -a letsencrypt-s3front:auth \
 --letsencrypt-s3front:auth-s3-bucket $S3_BUCKET \
 --letsencrypt-s3front:auth-s3-region $S3_REGION \
 -i letsencrypt-s3front:installer \
 --letsencrypt-s3front:installer-cf-distribution-id $CF_DISTRIBUTION \
 -d $(echo ${LE_DOMAIN//,/ -d }) \
-m $LE_EMAIL \
 --renew-by-default --text \
--work-dir ./le/work \
--cert-path ./le/cert \
--key-path ./le/key \
--config-dir ./le/config \
--logs-dir ./le/logs
```

**Comment by visibilityspots** [comment]
@devjack I tried that as I explained in the initial issue commit. But for me that fails as you could read above..

**Comment by visibilityspots** [comment]
but apparently this error doesn't pop up anymore and I just got a certificate for both domain names with the -d parameter.
