### ISSUE TITLE
Allow custom s3 bucket region_name

### ISSUE THREAD

**Issue by tsing** [dlapiduz/letsencrypt-s3front#3]
My s3 bucket is created in ap-northeast-1, and I have to modify the code in authenticator.py to pass addition parameters to boto3.resource to make it work:

```
s3 = boto3.resource('s3', region_name='ap-northeast-1')
```

**Comment by dlapiduz** [comment]
Just merged https://github.com/dlapiduz/letsencrypt-s3front/pull/9 that lets you do exactly this.

Thanks @moebiuz!
