### ISSUE TITLE
cant renew!!! urgent!

### ISSUE THREAD

**Issue by ChrisFernandez** [dlapiduz/letsencrypt-s3front#37]
An unexpected error occurred:
DialogError
Please see the logfiles in /var/log/letsencrypt for more details.

attach is the log file 
[letsencrypt.txt](https://github.com/dlapiduz/letsencrypt-s3front/files/412678/letsencrypt.txt)

**Comment by ChrisFernandez** [comment]
no help? even with log :cry:

**Comment by paulwakeford** [comment]
I think the issue is your cert has already expired and the renewal process expects the cert to still be valid. Try removing your invalid cert and creating a new cert.

**Comment by ChrisFernandez** [comment]
ok I try that as soon I get to my home later, hopefully is that simple. thank you..
I will update if it works.

**Comment by ChrisFernandez** [comment]
I got a bunch of errors.. but it seemed to has worked... the first time I did it also got errors..but worked so did not follow up.
