### ISSUE TITLE
can the authenticator be run without running the installer?

### ISSUE THREAD

**Issue by ezeeetm** [dlapiduz/letsencrypt-s3front#4]
Is it possible to run something like 

AWS_ACCESS_KEY_ID="your_key" \
AWS_SECRET_ACCESS_KEY="your_secret" \
letsencrypt --agree-tos -a letsencrypt-s3front:auth \
--letsencrypt-s3front:auth-s3-bucket the_bucket \
-d the_domain

to run just the authenticator part and not the installer?

I can then use an http redirect from my web server to the auth file in s3.  This is useful for our situation where we have hundreds of domains behind one ELB, so we can avoid creating symlinks to --webroot directory

**Comment by dlapiduz** [comment]
Yes you can!

Just run the CLI with the `certonly` command...

So something like: 

```
AWS_ACCESS_KEY_ID="your_key" \
AWS_SECRET_ACCESS_KEY="your_secret" \
letsencrypt --agree-tos -a letsencrypt-s3front:auth \
--letsencrypt-s3front:auth-s3-bucket the_bucket \
-d the_domain certonly
```

**Comment by ezeeetm** [comment]
@dlapiduz thx.  this is good.
