### ISSUE TITLE
Allows illegal certs to be uploaded

### ISSUE THREAD

**Issue by ryansb** [dlapiduz/letsencrypt-s3front#6]
CloudFront (regrettably) only supports 2048 bit keys, per [this](https://community.letsencrypt.org/t/certificate-is-not-working-with-cloudfront/4711), but letsencrypt-s3front happily lets me upload (to IAM) a 4096 bit certificate. 

It would be great if it could raise an error message when it is run against a key over 2048 bit and stop, rather than trying to update the distribution and failing.

**Comment by dlapiduz** [comment]
@ryansb that is interesting. I wonder if you can get that info from the `letsencrypt` client.... or inspecting the key.

Let me take a look at it

**Comment by jareware** [comment]
I'm getting:

```
An unexpected error occurred:
ClientError: An error occurred (InvalidViewerCertificate) when calling the UpdateDistribution operation: Your IAMCertificateId does not match the given Certificate field.
```

I wonder if this might be the same issue?

**Comment by dlapiduz** [comment]
This should be fixed now.
